### ISSUE TITLE
Camera animations

### ISSUE THREAD

**Issue by Youzid** [lucafanselau/jongleur#8] opened 2022-12-30 20:28 UTC
- if the scroll doesn't stop  exactly at  a mentioned point  in the Orchestrate Function  the camera will skips frames and struggle
- in this example  :  if you scroll to 0.5 , 1 ,1.5 , 2.5  ...  the camera will skip frames at the end of those points

![image](https://user-images.githubusercontent.com/38731876/210108631-bb41949c-1861-4bed-ad06-5de022693494.png)

with the usage of sanping you won't have this issues because you will  snap exactly to those points but if you spam scroll snap you will see the camera struggling , it would be great to make the camera wait the previous animations , or at least have a delay between snaps

**Comment by fanselau** [comment] 2022-12-31 14:30
This was actually caused by multiple clips happening after one another when damping is enabled. Should be fixed as of version: 0.2.0

**Closed as completed** 2022-12-31 14:30 UTC
